name: jinja_reflectable
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  jinja: ^0.2.0
  reflectable: ^2.2.1+2

dev_dependencies:
  build_runner: ^1.7.3
  pedantic: ^1.8.0
